/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.animalcentre;

import animalcentre.Customer;
import animalcentre.CustomerManagerImpl;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.sql.DataSource;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author blurry
 */
public class CustomerEditUI extends javax.swing.JFrame {
    
    private Customer customer;
    private DataSource dataSource;
    private static Logger logger;

    /**
     * Creates new form CustomerEditUI
     */
    public CustomerEditUI() {
        initComponents();
    }
    
    CustomerEditUI(Customer custom, DataSource dataSource, final Logger logger) {
        initComponents();
        
        this.customer = custom;
        this.dataSource = dataSource;
        this.logger = logger;
        
        setToCustom(custom);
        
        // for logging uncaught exceptions
        Thread.setDefaultUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
            public void uncaughtException(Thread t, Throwable e) {
                logger.log(Level.SEVERE, "Uncaught Exception in thread '" + t.getName() + "'", e);
                System.exit(1);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelName = new java.awt.Label();
        labelAddress = new java.awt.Label();
        labelPhone = new java.awt.Label();
        textFieldName = new javax.swing.JTextField();
        textFieldAddress = new javax.swing.JTextField();
        textFieldPhone = new javax.swing.JTextField();
        buttonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Main/resources/Bundle"); // NOI18N
        labelName.setText(bundle.getString("NAME: ")); // NOI18N

        labelAddress.setText(bundle.getString("ADDRESS:")); // NOI18N

        labelPhone.setText(bundle.getString("PHONE NUMBER:")); // NOI18N

        textFieldName.setText(bundle.getString("JTEXTFIELD1")); // NOI18N

        textFieldAddress.setText(bundle.getString("JTEXTFIELD2")); // NOI18N

        textFieldPhone.setText(bundle.getString("JTEXTFIELD3")); // NOI18N

        buttonOK.setText(bundle.getString("OK")); // NOI18N
        buttonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonOK)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(textFieldAddress)
                            .addComponent(textFieldPhone))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(buttonOK)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOKActionPerformed
        Customer customer = this.customer;
        String formerCustomer = this.customer.toString();
        customer = getCustomer(customer);
        
        if (customer != null) {
            CustomerManagerImpl manager = new CustomerManagerImpl(dataSource);
            manager.updateCustomer(customer);
            logger.log(Level.INFO, "Customer [{0}] updated to: {1}; formerly was {2}", new Object[]{String.valueOf(customer.getCustomerID()), customer, formerCustomer});
            this.dispose();
        }
    }//GEN-LAST:event_buttonOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (java.util.ResourceBundle.getBundle("Main/resources/Bundle").getString("NIMBUS").equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerEditUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerEditUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerEditUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerEditUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerEditUI().setVisible(true);
            }
        });
    }
    
    private void setToCustom(Customer custom) {
        textFieldName.setText(custom.getName());
        textFieldAddress.setText(custom.getAddress());
        textFieldPhone.setText(custom.getPhoneNumber());
    }

    public Customer getCustomer(Customer customer) {

        CustomerManagerImpl manager = new CustomerManagerImpl(dataSource);

        Pattern p = Pattern.compile("[A-Za-zĚŠČŘŽÝÁÍÍÉŤÚÄÔŮŇÓĹŔěščřžýáÍíéťúňóĺŕ ]*\\d*");
        Pattern addre = Pattern.compile("\\d*[A-ZĚŠČŘŽÝÁÍÉŤÚŇÓĹŔa-zěščřžýáÍíéťúňóĺŕ ]*\\d*");
        Pattern phon = Pattern.compile("[+]?\\d*");
        String name = textFieldName.getText();
        String address = textFieldAddress.getText();
        String phone = textFieldPhone.getText();

        if (name.equals("")) {
            JOptionPane.showMessageDialog(new JFrame(LanguageWizard.getString("Message")), LanguageWizard.getString("You_must_set_the_name"));
        } else {
            if (!p.matcher(name).matches()) {
                JOptionPane.showMessageDialog(new JFrame(LanguageWizard.getString("Message")), LanguageWizard.getString("Pattern_not_match_cus"));
            } else {
                customer.setName(textFieldName.getText());

                if (address.equals("")) {
                    JOptionPane.showMessageDialog(new JFrame(LanguageWizard.getString("Message")), LanguageWizard.getString("You_must_set_the_address"));
                } else {
                    if (!addre.matcher(address).matches()) {
                        JOptionPane.showMessageDialog(new JFrame(LanguageWizard.getString("Message")), LanguageWizard.getString("Pattern_not_match_address"));
                    } else {
                        customer.setAddress(textFieldAddress.getText());

                        if (phone.equals("")) {
                            JOptionPane.showMessageDialog(new JFrame(LanguageWizard.getString("Message")), LanguageWizard.getString("You_must_set_the_phone"));
                        } else {
                            if (!phon.matcher(phone).matches()) {
                                JOptionPane.showMessageDialog(new JFrame(LanguageWizard.getString("Message")), LanguageWizard.getString("Pattern_not_match_phone"));
                            } else {
                                customer.setPhoneNumber(textFieldPhone.getText());

                                if (customer == null) {
                                    JOptionPane.showMessageDialog(new JFrame(LanguageWizard.getString("Message")), LanguageWizard.getString("can_NOT_be_null")); // ??
                                    throw new IllegalArgumentException(LanguageWizard.getString("can_NOT_be_null"));
                                }
                                
                                return customer;
                            }
                        }
                    }
                    
                }
            }
        } return null;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOK;
    private java.awt.Label labelAddress;
    private java.awt.Label labelName;
    private java.awt.Label labelPhone;
    private javax.swing.JTextField textFieldAddress;
    private javax.swing.JTextField textFieldName;
    private javax.swing.JTextField textFieldPhone;
    // End of variables declaration//GEN-END:variables
}
